### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by infredulous** [AnthonyRonning/satreon#12]
Change from Litreon to Satreon (unless intentional)

**Comment by infredulous** [comment]
:-)

**Comment by AnthonyRonning** [comment]
It was originally intention due to links in other places, but yeah I should rename it now and update the app to point to this location, thanks for reminding me.

**Comment by AnthonyRonning** [comment]
Looks like GitHub does some redirection automatically for renamed repo's, so no problem there. thanks!
